"""add virtues

Revision ID: 2d2a9aa88542
Revises: 4b1b596db73b
Create Date: 2016-05-06 17:30:56.688792

"""

# revision identifiers, used by Alembic.
revision = '2d2a9aa88542'
down_revision = '4b1b596db73b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_path', sa.String(length=750), nullable=False),
    sa.Column('illustration_path', sa.String(length=750), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtues')
    ### end Alembic commands ###
