"""add_user

Revision ID: 8c30e0f375cb
Revises: a4a1eddab77b
Create Date: 2016-05-16 23:32:58.206412

"""

# revision identifiers, used by Alembic.
revision = '8c30e0f375cb'
down_revision = 'a4a1eddab77b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.add_column('virtues', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtues', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtues', type_='foreignkey')
    op.drop_column('virtues', 'user_id')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    ### end Alembic commands ###
