"""add_user_to_post

Revision ID: a4a1eddab77b
Revises: b26df72b985a
Create Date: 2016-05-16 23:19:06.021224

"""

# revision identifiers, used by Alembic.
revision = 'a4a1eddab77b'
down_revision = 'b26df72b985a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    ### end Alembic commands ###
