"""alter_password

Revision ID: b26df72b985a
Revises: da4cc1a57134
Create Date: 2016-05-16 23:01:07.361598

"""

# revision identifiers, used by Alembic.
revision = 'b26df72b985a'
down_revision = 'da4cc1a57134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.drop_table('users')
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('_password', sa.Binary(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    ### end Alembic commands ###


def downgrade():
    pass
