"""add_commitments

Revision ID: ee2713a1acf0
Revises: 8c30e0f375cb
Create Date: 2016-05-23 20:58:29.815103

"""

# revision identifiers, used by Alembic.
revision = 'ee2713a1acf0'
down_revision = '8c30e0f375cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('virtue_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_started', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['virtue_id'], ['virtues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commitments')
    ### end Alembic commands ###
